pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'KikuGie'
			url = 'https://maven.kikugie.dev/releases'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'dev.kikugie.stonecutter' version '0.9.6'
}

stonecutter {
	create(rootProject) {
		versions '1.20.1', '1.20.4', '1.20.6',
				'1.21.1', '1.21.4', '1.21.5', '1.21.8',
				'1.21.10', '1.21.11', '26.1.2', '26.2'
		vcsVersion = '26.2'
	}
}

// Should match your modid
rootProject.name = 'svco'
