minecraft_version=1.21.4
fabric_api_version=0.119.4+1.21.4
svc_artifact=fabric-1.21.4-2.6.20
java_release=21
minecraft_range=~1.21.4
mixin_java_level=JAVA_21
modmenu_version=13.0.4
voicechat_api_version=2.6.20
voicechat_dep=>=1.21.4-2.6.20

# Minecraft versions this jar is published for on Modrinth
modrinth_game_versions=1.21.4
